/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:9f845502-93f3-4545-a4ee-c48037ca9717",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_SHCYbwIQy",
    "aws_user_pools_web_client_id": "212bm2k6jfecgajil4760gqanl",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3ca2prgmqrerjeefrj5v6ug56i.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
